"""
This module defines all the possible enumeration values of return code
"""

# general usage

"""
SUCCESS
"""
RET_SUCCESS = r'SUCCESS'

"""
TEST FAILURE (Suspected)
UNKNOWN FAILURE
"""
RET_TEST_FAIL = r'TEST_FAIL'
"""
ENV FAILURE
"""
RET_ENV_FAIL = r'ENV_FAIL'
"""
input parameters are invalid
"""
RET_INVALID_INPUT = r'INVALID_INPUT'

# return OS message

TYPE_EXECUTE = 'EXECUTE'
TYPE_KILL = 'KILL'
TYPE_REBOOT = 'REBOOT'
TYPE_SHUTDOWN = 'SHUTDOWN'
TYPE_STANDBY = 'STANDBY'
TYPE_HIBERNATE = 'HIBERNATE'
TYPE_DELETE = 'DELETE'
TYPE_EXECUTE_ASYNC = 'EXECUTE_ASYNC'
TYPE_WRITE = "WRITE"
TYPE_OPEN_FOR_READ = "OPEN_FOR_READ"
TYPE_OPEN_FOR_WRITE = "OPEN_FOR_WRITE"
TYPE_READ = "READ"
TYPE_CLOSE = "CLOSE"

TYPE_ENTEROS = 'ENTEROS'
TYPE_RESPONSE = 'RESPONSE'
